In [1]:
#imoorting libraries
import pandas as pd

In [2]:
#opening file in pandas
df = pd.read_csv(r"C:\Users\sebbi\Downloads\mymoviedb (1).csv",lineterminator="\n")
df.columns = df.columns.str.strip()

In [3]:
#checking data via head() command
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,12/15/2021,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,3/1/2022,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2/25/2022,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,11/24/2021,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,12/22/2021,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [4]:
#checking columns and types of the fullset of data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9837 non-null   object
 1   Title              9828 non-null   object
 2   Overview           9828 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   object
 5   Vote_Average       9827 non-null   object
 6   Original_Language  9827 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9837 non-null   object
dtypes: float64(1), object(8)
memory usage: 691.8+ KB

In [5]:
 #removes Overview and Poster_Url from data set as a part of the data cleaning process.
df = df.drop(columns = ["Overview","Poster_Url"])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9837 non-null   object
 1   Title              9828 non-null   object
 2   Popularity         9827 non-null   float64
 3   Vote_Count         9827 non-null   object
 4   Vote_Average       9827 non-null   object
 5   Original_Language  9827 non-null   object
 6   Genre              9826 non-null   object
dtypes: float64(1), object(6)
memory usage: 538.1+ KB

In [7]:
#checks for duplicates in: Title & null values in dataset
print(df.isna().sum())
print("end check for nulls")
df["Title"].duplicated().sum()

Release_Date          0
Title                 9
Popularity           10
Vote_Count           10
Vote_Average         10
Original_Language    10
Genre                11
dtype: int64
end check for nulls

np.int64(322)

In [8]:
#Checking the duplicate dataset considering the context of this Netflix movie data set it could be the duplicates are remakes and are unique movies
check_duplicates = df[df["Title"].duplicated(keep=False)]
check_duplicates.sort_values("Title").head(50)
#confirmed that there are either sequels or remakes of movies.

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Original_Language,Genre
3280,5/22/2015,365 Days,28.341,12,4.8,te,Romance
1434,2/7/2020,365 Days,52.418,6540,7,pl,"Drama, Romance"
6003,10/9/1984,A Christmas Carol,18.546,241,7.3,en,"Drama, Fantasy, TV Movie, Family"
2062,11/4/2009,A Christmas Carol,39.916,3732,6.9,en,"Animation, Family, Drama, Fantasy"
2179,4/30/2010,A Nightmare on Elm Street,38.399,2187,5.5,en,"Horror, Mystery, Thriller"
1609,11/9/1984,A Nightmare on Elm Street,48.070,3877,7.3,en,Horror
3713,6/24/2016,Adventures in Babysitting,25.885,316,7.4,en,"TV Movie, Comedy, Family"
5912,7/1/1987,Adventures in Babysitting,18.722,491,6.8,en,Comedy
1093,8/4/2021,Aftermath,61.846,402,6.5,en,"Horror, Crime, Drama, Thriller"
3576,2/28/2017,Aftermath,26.631,725,5.7,en,"Drama, Thriller"
9143,9/1/2016,Akira,14.017,30,6,hi,"Action, Crime, Thriller"
1521,7/16/1988,Akira,50.144,3022,8,ja,"Animation, Science Fiction, Action"
615,5/22/2019,Aladdin,91.942,8421,7.1,en,"Adventure, Fantasy, Romance, Family"
745,11/25/1992,Aladdin,79.961,9508,7.6,en,"Animation, Family, Adventure, Fantasy, Romance"
995,3/3/2010,Alice in Wonderland,65.738,11960,6.6,en,"Family, Fantasy, Adventure"
7809,2/28/1999,Alice in Wonderland,15.507,290,6.3,en,"Fantasy, Family"
769,7/28/1951,Alice in Wonderland,78.653,4852,7.2,en,"Animation, Family, Fantasy, Adventure"
9526,12/18/1933,Alice in Wonderland,13.627,34,6.2,en,"Adventure, Family, Fantasy"
6675,10/16/2020,Alone,17.236,116,5.9,en,"Horror, Thriller"
792,9/10/2020,Alone,77.506,403,6.2,en,"Thriller, Horror"
9012,4/14/2017,Altitude,14.136,95,4.8,en,"Action, Thriller"
9204,10/10/2010,Altitude,13.964,180,4.8,en,"Horror, Action, Thriller, Science Fiction"
6517,12/8/1964,Angelique,17.561,136,6.9,fr,"Adventure, Romance, History"
9713,12/18/2013,Angelique,13.453,97,6.5,fr,"Adventure, Romance"
8536,10/13/2013,Anna,14.614,488,6.5,en,"Thriller, Drama"
2549,6/19/2019,Anna,34.398,2039,6.7,fr,"Thriller, Action"
2552,12/19/2014,Annie,34.353,1105,6.2,en,"Comedy, Drama, Family"
7943,6/18/1982,Annie,15.330,543,6.5,en,"Comedy, Drama, Family"
2722,12/14/2020,Army of One,32.609,52,5.1,en,Action
6123,11/4/2016,Army of One,18.301,219,5.3,en,Comedy
9775,7/17/1981,Arthur,13.401,317,6.5,en,"Comedy, Drama, Romance"
3834,4/8/2011,Arthur,25.298,602,5.6,en,"Comedy, Romance"
774,8/12/2021,Assassins,78.513,6,7.3,en,Documentary
6490,10/6/1995,Assassins,17.607,1187,6.4,en,"Action, Adventure, Crime, Thriller"
223,7/2/2020,Ava,173.205,1917,5.7,en,"Action, Crime, Drama, Thriller"
162,6/21/2017,Ava,210.438,130,6,fr,Drama
6088,11/28/2007,Awake,18.372,1074,6.4,en,"Thriller, Crime, Mystery"
6316,8/1/2019,Awake,17.924,91,5.2,en,Thriller
405,6/9/2021,Awake,121.733,796,6,en,"Drama, Science Fiction, Thriller"
8180,3/25/1983,Bad Boys,15.018,190,7,en,"Crime, Drama, Thriller"
1309,4/7/1995,Bad Boys,55.763,5088,6.8,en,"Action, Comedy, Crime, Thriller"
6668,9/5/2012,Bait,17.254,609,5.7,en,"Action, Horror, Thriller"
7765,9/15/2000,Bait,15.567,146,5.7,en,"Action, Thriller, Crime"
72,6/23/1989,Batman,338.272,6109,7.2,en,"Fantasy, Action"
9328,7/16/1943,Batman,13.818,28,6.6,en,"Action, Adventure, Crime, Science Fiction, Thr..."
1601,7/30/1966,Batman,48.251,625,6.3,en,"Family, Adventure, Comedy, Science Fiction, Crime"
3006,2/12/2014,Beauty and the Beast,30.170,1763,6.1,fr,"Fantasy, Romance"
5771,10/29/1946,Beauty and the Beast,19.024,449,7.5,fr,"Drama, Fantasy, Romance"
506,3/16/2017,Beauty and the Beast,104.094,13992,7,en,"Family, Fantasy, Romance"
467,10/22/1991,Beauty and the Beast,109.649,8280,7.7,en,"Romance, Family, Animation, Fantasy"

In [9]:
#changing release date to datetime value, and confirming successful output: dtype('<M8[ns]')
df["Release_Date"] = pd.to_datetime(df["Release_Date"],errors='coerce')
df["Release_Date"].dtype

dtype('<M8[ns]')